### ISSUE TITLE
FASTQ files for Supplementary Table 4

### ISSUE THREAD

**Issue by CDieterich** [novoalab/Nano-tRNAseq#1]
Hi @lpryszcz 

congratulations on your manuscript !

I would like to go through your analysis that produces STable 4.
I have checked the EBI repository: https://www.ebi.ac.uk/ena/data/view/PRJEB55684 
but there are no FASTQ files, only archives with FAST5 files.

Could you kindly share the FASTQ files for 3_NanotRNAseq_IVT+tRNAphe.tar.gz and 4_NanotRNAseq_IVT+tRNAphe.tar.gz with me ?

Thank you.

**Comment by CDieterich** [comment]
Hi Lucas,

tried that in 4_NanotRNAseq_IVT
nanopolish extract -o bla FAQ42155_3bd137b7_18.fast5

[extract] found 1 files, extracted 0 reads

Does not seem to work or am I doing something wrong ?

**Comment by lpryszcz** [comment]
Hi @CDieterich , please try `fast5_to_fastq.py` from https://github.com/lpryszcz/bin : 

```bash
pip install ont_fast5_api
fast5_to_fastq.py -i workspace/*.fast5 | gzip > reads.fq.gz
```

For me it correctly retrieves FastQ reads from 4_NanotRNAseq_IVT+tRNAphe.tar.gz.

**Comment by CDieterich** [comment]
Hi @lpryszcz - thanks this worked for me.
