### ISSUE TITLE
question about the parameters in Minknow configure file

### ISSUE THREAD

**Issue by xieyy46** [novoalab/Nano-tRNAseq#2]
Hi developer!
I am so confused about the parameters in the part analysis_configuration.read_classification in the Minknow configure file (as showed in below picture),  would you please tell the details what median, local_median, median_before,local_range ect. mean ? And how dose this setting work to classify read？
![image](https://github.com/novoalab/Nano-tRNAseq/assets/76148123/32270bdb-eece-415f-95be-4082a194d910)

**Comment by xieyy46** [comment]
Hi lpryszcz, Thank you for your reply!  By the way, do you know how adaptor signals were trimmed when using guppy basecalling for dRNA sequencing?

**Comment by enovoa** [comment]
Hi @xieyy46, for details on how guppy or other ONT-specific software works, please ask directly to ONT via their community, as @lpryszcz already mentioned in this previous response. Thanks!
