### ISSUE TITLE
Config path differences on MacOS

### ISSUE THREAD

**Issue by lkwhite** [novoalab/Nano-tRNAseq#3]
FYI for anyone else running on a Mac instead of Linux machine, the location for MinKNOW config files is different. The below should work for MacOS:

```
sudo rsync -a conf/package/flow_cells.toml /Applications/MinKNOW.app/Contents/Resources/conf/package
sudo rsync -a conf/package/sequencing/*.toml /Applications/MinKNOW.app/Contents/Resources/conf/package/sequencing
```

Thanks again for solving this short read RNA issue!

**Comment by lpryszcz** [comment]
thx @lkwhite ! 
already added to documentation!
