### ISSUE TITLE
Can we use this alternative configuration file in MinKnow standalone software for MinION Mk1B?

### ISSUE THREAD

**Issue by shengqh** [novoalab/Nano-tRNAseq#4]
We generated bulk fast5 files based on your introduction. Now we want to perform analysis in simulation mode. We installed the MinKnow standalone software downloaded from Nanopore website in another powerful workstation. When I started the MinKNOW UI, I found "My device" with "No positions connected" in connection manager. So I cannot do the analysis in simulation mode since there is no flowcell dropbox that I can select the alternative configuration. Do we have to import the alternative configuration files to the MinKNOW in the real MinION device? Thank you so much.

**Comment by lpryszcz** [comment]
Hi @shengqh, 

You should connect MinION device with a flowcell 
Sorry, this detail was omitted. Update the docs.
