### ISSUE TITLE
Config settings for Promethion?

### ISSUE THREAD

**Issue by lkwhite** [novoalab/Nano-tRNAseq#7]
I'm trying to make changes to config file to permit short mode sequencing and/or simulation on a Promethion. A first naive attempt was to just try adding Promethion flow cells to [flow_cells.toml](https://github.com/novoalab/Nano-tRNAseq/commit/b0c9f25330d12b3395c925730fccbdcc6246a2aa) and then add "FLO-PRO002_short" to `sequencing_MIN106_RNA_short.toml`. However, when we actually try to start a run with this short read mode, we get through the flow cell check and then almost immediately drop to zero pores. My suspicion is that one or more of the settings in this file (target temperature? min/max voltage?) are MinION specific and incompatible with Promethion settings, causing the pores to register as nonfunctional once the run starts.

Have you all played with settings for the Promethion at all? I shot an email to ONT customer support too, but that's always hit or miss.

**Comment by lpryszcz** [comment]
Hi Laura, custom flowcell configurations didn't work with actual sequencing for us. You need to run sequencing with default config, save bulk file and run seqeuncing simulations with alternative config. 
I know, it's troublesome, but we were unable to make it easier... 
We haven't tried it with PromethION yet. Please let us know if it worked for you. 
Greetings from Barcelona!

**Comment by lkwhite** [comment]
Oh, interesting! I saw the note that custom configurations can be used only with sequencing simulations, but naively tried a run in short mode using a Flongle flow cell and it worked just fine for sequencing & base-calling in real time. I wonder why?

**Comment by lpryszcz** [comment]
hah, that's peculiar. we neither tried with flongle I guess. or if we did, we just saved bulk and reprocess it. good to know!
