### ISSUE TITLE
Config Files for the SQK-RNA004 Kit with the MinION RNA Flowcell

### ISSUE THREAD

**Issue by hd2326** [novoalab/Nano-tRNAseq#9]
Greetings!

I am wondering if you have the config files for the SQK-RNA004 kit with the MinION RNA flowcell.

Or would you please point me which several key items you have changed/added in the sequencing_MIN106_RNA_short.toml?

Thank you very much in advance for your help!

**Comment by lpryszcz** [comment]
see #5
